name:                discord-hs
version:             0.2.2
synopsis:            An API wrapper for Discord in Haskell
description:         Provides an api wrapper and framework for writing
                     bots against the Discord <https://discordapp.com/> API.
                     If for some reason hackage/stackage is failing to build
                     documentation, a backup set is hosted at <https://jano017.github.io/Discord.hs/>
homepage:            https://github.com/jano017/Discord.hs
license:             MIT
license-file:        LICENSE
author:              Joshua Koike
maintainer:          jkoike2013@gmail.com
copyright:           Joshua Koike
category:            Network
# build-type:          Simple
# extra-source-files:
# cabal-version:       >=1.10
# default-language:    Haskell2010

flags:
  docs:
    description:	Disable documentation generation
    manual:		true
    default:		false

library:
  source-dirs:		src
  ghc-options:         -Wall
dependencies:
  - base
  - aeson >= 1.2
  - discord-types
  - discord-rest
  - discord-gateway
  - hashable
  - mtl
  - url >= 2.1
  - websockets
  - pandoc

# executables:
#   docs:
#     main:             Site.hs
#     source-dirs:      docs
#     when:
#       - condition: flag(docs)
#         then:
#           dependencies:
#             - base==4.*
#             - hakyll
#             - split
#         else:
#           buildable:         false
#     ghc-options:         -Wall
