name:                discord-hs
version:             0.2.2
synopsis:            An API wrapper for Discord in Haskell
description:         Provides an api wrapper and framework for writing
                     bots against the Discord <https://discordapp.com/> API.
                     If for some reason hackage/stackage is failing to build
                     documentation, a backup set is hosted at <https://jano017.github.io/Discord.hs/>
homepage:            https://github.com/jano017/Discord.hs
license:             MIT
license-file:        LICENSE
author:              Joshua Koike
maintainer:          jkoike2013@gmail.com
copyright:           Joshua Koike
category:            Network

flags:
  docs:
    description:	Disable documentation generation
    manual:		true
    default:		false

library:
  source-dirs: 		src
  ghc-options:          -j -Wall
  exposed-modules:      Network.Discord
  dependencies:
    - base
    - aeson >= 1.2
    - discord-types
    - discord-rest
    - discord-gateway
    - hashable
    - mtl
    - websockets

executables:
  docs:
    source-dirs:      docs
    main:             Site.hs
    when:
      - condition: flag(docs)
        then:
          dependencies:
            - split
            - hakyll
        else:
          buildable:         false
    ghc-options:         -Wall
  hello_world:
    source-dirs:	examples
    main:		hello_world.hs
    dependencies:
      - base
      - discord-hs
  pingpong:
    source-dirs:	examples
    main:		pingpong.hs
    dependencies:
      - base
      - discord-hs
      - req
      - text
      
