allow-newer: true
extra-deps:
  - url-2.1.3
  - hakyll-4.12.1.0
  - fsnotify-0.2.1.1
  - hinotify-0.3.9
  - async-2.1.1.1
  - pandoc-2.1.3
extra-package-dbs: []
packages:
- '.'
- './discord-types'
- './discord-rest'
- './discord-gateway'
resolver: nightly-2018-04-09
nix:
  packages: [ zlib, gmp, unzip ]
